/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DB.Journal;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author REEN
 */
public class AddDawryah extends javax.swing.JFrame {

    /**
     * Creates new form AddDawryah
     */
    public AddDawryah() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        label = new javax.swing.JTextField();
        c_num = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pages = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        copy = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        publisher = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        startD = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        EndD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        PDate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        typeR = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        label_type = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        part = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(187, 191, 202));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("تسجيل الخروج");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 120, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("* عنوان الدورية");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 140, 30));

        label.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 360, 40));

        c_num.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(c_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 200, 40));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("* رقم التصنيف");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 120, 30));

        pages.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(pages, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 170, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("عدد الصفحات");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 120, 30));

        copy.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(copy, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 170, 40));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("* عدد النسخ");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 100, 30));

        publisher.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 360, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("* الناشر");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 70, 30));

        city.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 200, 40));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setText("مكان النشر");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 90, 30));

        startD.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(startD, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 200, 40));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setText("سنة الصدور");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 110, 30));

        EndD.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(EndD, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 200, 40));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("سنة التوقف");
        jLabel10.setToolTipText("");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 100, 30));

        PDate.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(PDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 170, 40));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel15.setText("سنة صدور العدد");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, 140, 30));

        typeR.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(typeR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 170, 40));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel16.setText("نوع فترات الصدور");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 160, 30));

        label_type.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(label_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 200, 40));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("نوع التصنيف");
        jLabel11.setToolTipText("");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 120, 30));

        jButton9.setBackground(new java.awt.Color(73, 84, 100));
        jButton9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton9.setText("اضافة");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, 250, 60));

        jButton13.setBackground(new java.awt.Color(73, 84, 100));
        jButton13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton13.setText("مسح الكل");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, 250, 60));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel14.setText("إضافة دورية");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 210, 50));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setText("عدد الاجزاء");
        jLabel18.setToolTipText("");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 120, 30));

        part.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(part, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 200, 40));

        jButton17.setBackground(new java.awt.Color(187, 191, 202));
        jButton17.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton17.setText("اضافة الى المكتبة");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 80, 270, 60));

        jButton2.setBackground(new java.awt.Color(187, 191, 202));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton2.setText("البحث في المكتبة");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 270, 60));

        jButton3.setBackground(new java.awt.Color(187, 191, 202));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton3.setText("بيانات المكتبة");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 220, 270, 60));

        jButton4.setBackground(new java.awt.Color(187, 191, 202));
        jButton4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton4.setText("بيانات المستعيرين ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 290, 270, 60));

        jButton15.setBackground(new java.awt.Color(187, 191, 202));
        jButton15.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton15.setText(" الاعارة");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 360, 270, 60));

        jButton5.setBackground(new java.awt.Color(187, 191, 202));
        jButton5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton5.setText("الاسترجاع");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 430, 270, 60));

        jButton6.setBackground(new java.awt.Color(187, 191, 202));
        jButton6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton6.setText("البحث في بيانات الاعارة");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 500, 270, 60));

        jButton7.setBackground(new java.awt.Color(187, 191, 202));
        jButton7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton7.setText("التقارير");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 570, 270, 60));

        jButton8.setBackground(new java.awt.Color(187, 191, 202));
        jButton8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton8.setText("النسخ الاحتياطي");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 640, 270, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/insert_book - Copy.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int r = JOptionPane.showConfirmDialog(this, "هل تريد تسجيل الخروج؟", "تأكيد", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (r == JOptionPane.YES_OPTION) {
           
            new User().setVisible(true);
             this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
         boolean check = true;
        boolean done = false;
        boolean c1 = false, c2 = false, c3 = false, c4 = false, c5 = false, c6 = false;
        Pattern pattern;
        Matcher match;
        boolean val;
        if (this.label.getText().trim().isEmpty() || this.c_num.getText().trim().isEmpty() || this.copy.getText().trim().isEmpty()
                || this.publisher.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "            من فضلك !!         \n"
                    + " تحقق من ان جميع البيانات الضرورية معبأه");
            check = false;
        }
        if (check == true) {
            //=================================
            if (pages.getText().trim().isEmpty()) {
                c1 = true;
            } else {
                pattern = Pattern.compile("[^0-9]");
                match = pattern.matcher(String.valueOf(pages.getText().trim()));

                val = match.find();
                if (val == true) {

                    JOptionPane.showMessageDialog(this, "يجب ادخال ارقام فقط في عدد الصفحات  ");
                } else {
                    c1 = true;
                }
            }
            //===================================

            pattern = Pattern.compile("[^0-9]");
            match = pattern.matcher(String.valueOf(copy.getText().trim()));

            val = match.find();
            if (val == true) {

                JOptionPane.showMessageDialog(this, "يجب ادخال ارقام فقط في عدد النسخ   ");
            } else {
                c2 = true;
            }
            //================================

            if (startD.getText().trim().isEmpty()) {
                c3 = true;
            } else {
                match = pattern.matcher(String.valueOf(startD.getText().trim()));

                val = match.find();
                if (val == true) {

                    JOptionPane.showMessageDialog(this, "يجب ادخال ارقام فقط في سنة الصدور  ");
                } else {
                    c3 = true;
                }
            }
            //================================

            if (EndD.getText().trim().isEmpty()) {
                c4 = true;
            } else {
                pattern = Pattern.compile("[^0-9]");
                match = pattern.matcher(String.valueOf(EndD.getText().trim()));

                val = match.find();
                if (val == true) {

                    JOptionPane.showMessageDialog(this, "يجب ادخال ارقام فقط في سنة التوقف  ");
                } else {
                    c4 = true;
                }
            }
            ///========================
            if (PDate.getText().trim().isEmpty()) {
                c5 = true;
            } else {
                pattern = Pattern.compile("[^0-9]");
                match = pattern.matcher(String.valueOf(PDate.getText().trim()));

                val = match.find();
                if (val == true) {

                    JOptionPane.showMessageDialog(this, "يجب ادخال ارقام فقط في سنة صدور العدد  ");
                } else {
                    c5 = true;
                }
            }
            //==========================
            if (part.getText().trim().isEmpty()) {
                c6 = true;
            } else {
                pattern = Pattern.compile("[^0-9]");
                match = pattern.matcher(String.valueOf(part.getText().trim()));

                val = match.find();
                if (val == true) {

                    JOptionPane.showMessageDialog(this, "يجب ادخال ارقام فقط في عدد الأجزاء  ");
                } else {
                    c6 = true;
                }
            }
            if (c1 && c2 && c3 && c4 && c5&&c6 == true) {
                done = true;
            }
        }
        if (done == true) {
            if (this.pages.getText().trim().isEmpty()) {
                this.pages.setText("0");
            }
            if (this.city.getText().trim().isEmpty()) {
                this.city.setText(null);
            }
            if (this.startD.getText().trim().isEmpty()) {
                this.startD.setText(null);
            }
            if (this.EndD.getText().trim().isEmpty()) {
                this.EndD.setText(null);
            }
            if (this.PDate.getText().trim().isEmpty()) {
                this.PDate.setText("0");
            }
            if (this.typeR.getText().trim().isEmpty()) {
                this.typeR.setText(null);
            }
            if (this.label_type.getText().trim().isEmpty()) {
                this.label_type.setText(null);
            }if (this.part.getText().trim().isEmpty()) {
                this.part.setText("0");
            }
            int resutl = JOptionPane.showConfirmDialog(this, "هل انت متأكده من جميع البيانات \n ", "رسالة تحذيرية !!!", JOptionPane.YES_NO_OPTION);
            if (resutl == JOptionPane.YES_OPTION) {

                Journal j = new Journal(Integer.parseInt(this.copy.getText()), this.c_num.getText(), this.startD.getText(),
                         this.EndD.getText(), Integer.parseInt(this.pages.getText()), this.label.getText(), this.label_type.getText(),
                         this.typeR.getText(), this.publisher.getText(), Integer.parseInt(this.PDate.getText()), this.city.getText(),Integer.parseInt(this.part.getText()));
                j.addJournal();
                int J_id = j.getJournal_ID(label.getText());
                JOptionPane.showMessageDialog(this, "عنوان الدورية :" + this.label.getText() + "\n"
                        + "الرقم العام: " + J_id);
                

            } else {
               


            }

        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
      
        new AddDawryah().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:

        new add().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        new Search_inLibrary1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        new Library_info1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        new SearchInBorrow_s_Info1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:

        new make_a_barow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        new Recovry().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        new SearchInBorrowInfo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        new report().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        new BackUp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDawryah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDawryah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDawryah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDawryah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDawryah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EndD;
    private javax.swing.JTextField PDate;
    private javax.swing.JTextField c_num;
    private javax.swing.JTextField city;
    private javax.swing.JTextField copy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField label;
    private javax.swing.JTextField label_type;
    private javax.swing.JTextField pages;
    private javax.swing.JTextField part;
    private javax.swing.JTextField publisher;
    private javax.swing.JTextField startD;
    private javax.swing.JTextField typeR;
    // End of variables declaration//GEN-END:variables
}
