/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DB.Book;
import DB.Borrowers;
import DB.Journal;
import DB.Messag;
import DB.Project;
import DB.borrowed;
import DB.borrower_type;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author REEN
 */
public class Recovry extends javax.swing.JFrame {

    /**
     * Creates new form Recovry
     */
    borrower_type Bt;
    Borrowers bB;
    Book book1 = new Book();
    Journal jr1 = new Journal();
    Project Project = new Project();
    Messag ms = new Messag();
    borrowed br = new borrowed();
    long days = 0;

    public Recovry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pr = new javax.swing.JRadioButton();
        cl = new javax.swing.JRadioButton();
        jButton11 = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jr = new javax.swing.JRadioButton();
        jen = new javax.swing.JRadioButton();
        sb = new javax.swing.JTextField();
        book = new javax.swing.JRadioButton();
        msg = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("رقم الوعاء");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 100, 30));

        pr.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pr.setText("مشروع");
        pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prActionPerformed(evt);
            }
        });
        jPanel1.add(pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 100, 40));

        cl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cl.setText("رقم التصنيف");
        cl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clActionPerformed(evt);
            }
        });
        jPanel1.add(cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 110, 40));

        jButton11.setBackground(new java.awt.Color(73, 84, 100));
        jButton11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton11.setText("استرجاع");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, 250, 60));

        ID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 360, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("الرقم الجامعي او الوظيفي");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 210, 30));

        jr.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jr.setText("دورية");
        jr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrActionPerformed(evt);
            }
        });
        jPanel1.add(jr, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 110, 40));

        jen.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jen.setText("الرقم العام");
        jen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenActionPerformed(evt);
            }
        });
        jPanel1.add(jen, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 100, 40));

        sb.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(sb, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 360, 40));

        book.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        book.setText("كتاب");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        jPanel1.add(book, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 110, 40));

        msg.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        msg.setText("رسالة");
        msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgActionPerformed(evt);
            }
        });
        jPanel1.add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 100, 40));

        jButton1.setBackground(new java.awt.Color(187, 191, 202));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("تسجيل الخروج");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 120, 40));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel12.setText("الإسترجاع");
        jLabel12.setToolTipText("");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 170, -1));

        jButton17.setBackground(new java.awt.Color(187, 191, 202));
        jButton17.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton17.setText("اضافة الى المكتبة");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, 270, 60));

        jButton2.setBackground(new java.awt.Color(187, 191, 202));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton2.setText("البحث في المكتبة");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, 270, 60));

        jButton3.setBackground(new java.awt.Color(187, 191, 202));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton3.setText("بيانات المكتبة");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 210, 270, 60));

        jButton4.setBackground(new java.awt.Color(187, 191, 202));
        jButton4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton4.setText("بيانات المستعيرين ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 280, 270, 60));

        jButton15.setBackground(new java.awt.Color(187, 191, 202));
        jButton15.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton15.setText(" الاعارة");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 350, 270, 60));

        jButton5.setBackground(new java.awt.Color(187, 191, 202));
        jButton5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton5.setText("الاسترجاع");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 420, 270, 60));

        jButton6.setBackground(new java.awt.Color(187, 191, 202));
        jButton6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton6.setText("البحث في بيانات الاعارة");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 490, 270, 60));

        jButton7.setBackground(new java.awt.Color(187, 191, 202));
        jButton7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton7.setText("التقارير");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 560, 270, 60));

        jButton8.setBackground(new java.awt.Color(187, 191, 202));
        jButton8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton8.setText("النسخ الاحتياطي");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 630, 270, 60));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("ثانيا: اختيار طريقة الاسترجاع");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("اولا: اختيار نوع الوعاء ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/insert_book - Copy.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int r = JOptionPane.showConfirmDialog(this, "هل تريد تسجيل الخروج؟", "تأكيد", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (r == JOptionPane.YES_OPTION) {
          
            new User().setVisible(true);
              this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        // TODO add your handling code here:
        msg.setSelected(false);
        jr.setSelected(false);
        pr.setSelected(false);
    }//GEN-LAST:event_bookActionPerformed

    private void msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgActionPerformed
        // TODO add your handling code here:
        book.setSelected(false);
        jr.setSelected(false);
        pr.setSelected(false);
    }//GEN-LAST:event_msgActionPerformed

    private void prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prActionPerformed
        // TODO add your handling code here:
        book.setSelected(false);
        jr.setSelected(false);
        msg.setSelected(false);
    }//GEN-LAST:event_prActionPerformed

    private void jenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenActionPerformed
        // TODO add your handling code here:
        cl.setSelected(false);
    }//GEN-LAST:event_jenActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        if (ID.getText().isEmpty() || sb.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, " الرجاء تعبئة جميع الحقول ");

        } else {

            int i = 0;
            bB = new Borrowers(Integer.parseInt(ID.getText()));
            Pattern pattern = Pattern.compile("[^0-9]");
            Matcher match = pattern.matcher(String.valueOf(bB.ID));

            boolean val = match.find();

            if (val == true) {

                JOptionPane.showMessageDialog(this, "عذرا يجب ادخال الرقم الجامعي او الوظيفي بشكل صحيح ");
            }

            
            boolean check = bB.search(bB.ID);

            if (check) {
                Bt = new borrower_type();
                Bt.search(bB.type);

            } else {
                JOptionPane.showMessageDialog(this, " رقم المستخدم غير موجود");
            }
            DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            LocalDateTime now = LocalDateTime.now();

            if (book.isSelected()) {
                if (cl.isSelected()) {
                    jen.setSelected(false);

                    String data = book1.serachForBookUsingClassification_number(sb.getText());
                    if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {

                        br.ViewBorrowed2(sb.getText(), Integer.parseInt(ID.getText()));

                        LocalDate localDate1 = LocalDate.parse(br.Date, df);
                        LocalDate localDate2 = LocalDate.parse(df.format(now), df);

                        days = Period.between(localDate1, localDate2).getDays();
                        System.out.println(days + "dayes heheh");

                        if (book1.Number_Of_copies_existed >= book1.Number_Of_actuel_copies) {
                            JOptionPane.showMessageDialog(this, " عذرا كل النسخ لهذا الوعاء موجودة في المكتبة");
                           
                            new Recovry().setVisible(true);
                             this.dispose();

                        } else if (br.day < days) {

                            JOptionPane.showMessageDialog(this, br.Date + " ايام من  " + br.day + "  متأخر من المفترض ارجاع الوعاء بعد ");
                            i = bB.retrieve(book1.book_ID, bB.ID);

                        } else {
                            i = bB.retrieve(book1.book_ID, bB.ID);
                        }
                    }

                } else if (jen.isSelected()) {

                    cl.setSelected(false);
                    try {
                        int sb1 = Integer.parseInt(sb.getText());
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, " يجب ادخال ارقام فقط");
                    }

                    String data = book1.serachForBookUsingID(Integer.parseInt(sb.getText()));
                    if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {

                        br.ViewBorrowed1(Integer.parseInt(sb.getText()), Integer.parseInt(ID.getText()));

                        LocalDate localDate1 = LocalDate.parse(br.Date, df);
                        LocalDate localDate2 = LocalDate.parse(df.format(now), df);

                        days = Period.between(localDate1, localDate2).getDays();
                        System.out.println(days + "dayes heheh");
                        if (book1.Number_Of_copies_existed >= book1.Number_Of_actuel_copies) {
                            JOptionPane.showMessageDialog(this, " عذرا كل النسخ لهذا الوعاء موجودة في المكتبة");
                          
                            new Recovry().setVisible(true);
                              this.dispose();

                        } else if (br.day < days) {

                            JOptionPane.showMessageDialog(this, br.Date + " ايام من  " + br.day + "  متأخر من المفترض ارجاع الوعاء بعد ");
                            i = bB.retrieve(book1.book_ID, bB.ID);

                        } else {
                            i = bB.retrieve(book1.book_ID, bB.ID);
                        }

                    }

                } else {

                    JOptionPane.showMessageDialog(this, " يجب اختيار احدى خيارات البحث اما الرقم العام او التصنيف");
                }

            } else if (msg.isSelected()) {
                if (cl.isSelected()) {
                    jen.setSelected(false);

                    String data = ms.serachForMsgUsingClassification_number(sb.getText());
                    if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {

                        br.ViewBorrowed2_l(sb.getText(), Integer.parseInt(ID.getText()));

                        LocalDate localDate1 = LocalDate.parse(br.Date, df);
                        LocalDate localDate2 = LocalDate.parse(df.format(now), df);

                        long days = Period.between(localDate1, localDate2).getDays();
                        System.out.println(days + "dayes heheh");

                        if (ms.Number_Of_copies_existed >= ms.Number_Of_actuel_copies) {
                            JOptionPane.showMessageDialog(this, " عذرا كل النسخ لهذا الوعاء موجودة في المكتبة");
                          
                            new Recovry().setVisible(true);
                              this.dispose();

                        } else if (br.day < days) {

                            JOptionPane.showMessageDialog(this, br.Date + " ايام من  " + br.day + "  متأخر من المفترض ارجاع الوعاء بعد ");
                            i = bB.retrieve_l(ms.msg_id, bB.ID);

                        } else {
                            i = bB.retrieve_l(ms.msg_id, bB.ID);
                        }}
                    

                    }else if (jen.isSelected()) {
                    cl.setSelected(false);
                    
                     try {
                        int sb1 = Integer.parseInt(sb.getText());
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, " يجب ادخال ارقام فقط");
                    }

                    String data = ms.serachForMsgUsingID(Integer.parseInt(sb.getText()));
                    if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {

                        br.ViewBorrowed1_l(Integer.parseInt(sb.getText()), Integer.parseInt(ID.getText()));

                        LocalDate localDate1 = LocalDate.parse(br.Date, df);
                        LocalDate localDate2 = LocalDate.parse(df.format(now), df);

                        long days = Period.between(localDate1, localDate2).getDays();
                        System.out.println(days + "dayes heheh");

                        if (ms.Number_Of_copies_existed >= ms.Number_Of_actuel_copies) {
                            JOptionPane.showMessageDialog(this, " عذرا كل النسخ لهذا الوعاء موجودة في المكتبة");
                           
                            new Recovry().setVisible(true);
                             this.dispose();

                        } else if (br.day < days) {

                            JOptionPane.showMessageDialog(this, br.Date + " ايام من  " + br.day + "  متأخر من المفترض ارجاع الوعاء بعد ");
                            i = bB.retrieve_l(ms.msg_id, bB.ID);

                        } else {
                            i = bB.retrieve_l(ms.msg_id, bB.ID);
                        }}
                
                
                    }else{
                         JOptionPane.showMessageDialog(this, " يجب اختيار احدى خيارات البحث اما الرقم العام او التصنيف");
                    }
            
            } else if (jr.isSelected()) {
                     if (cl.isSelected()) {
                    jen.setSelected(false);

                    String data = jr1.serachForJournalUsingClassification_number(sb.getText());
                    if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
                br.ViewBorrowed2_j(sb.getText(), Integer.parseInt(ID.getText()));

                LocalDate localDate1 = LocalDate.parse(br.Date, df);
                LocalDate localDate2 = LocalDate.parse(df.format(now), df);

                long days = Period.between(localDate1, localDate2).getDays();
                System.out.println(days + "dayes heheh");

                if (jr1.Number_Of_copies_existed >= jr1.Number_Of_actuel_copies) {
                    JOptionPane.showMessageDialog(this, " عذرا كل النسخ لهذا الوعاء موجودة في المكتبة");
                  
                    new Recovry().setVisible(true);
                      this.dispose();

                } else if (br.day < days) {

                    JOptionPane.showMessageDialog(this, br.Date + " ايام من  " + br.day + "  متأخر من المفترض ارجاع الوعاء بعد ");
                    i = bB.retrieve_j(jr1.Journal_ID, bB.ID);

                } else {
                    i = bB.retrieve_j(jr1.Journal_ID, bB.ID);
                }
                    }
              }else if (jen.isSelected()) {
                    cl.setSelected(false);
                    
                     try {
                        int sb1 = Integer.parseInt(sb.getText());
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, " يجب ادخال ارقام فقط");
                    }

                    String data = jr1.serachForJournalUsingID(Integer.parseInt(sb.getText()));
                    if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
                         br.ViewBorrowed1_j(Integer.parseInt(sb.getText()), Integer.parseInt(ID.getText()));

                LocalDate localDate1 = LocalDate.parse(br.Date, df);
                LocalDate localDate2 = LocalDate.parse(df.format(now), df);

                long days = Period.between(localDate1, localDate2).getDays();
                System.out.println(days + "dayes heheh");

                if (jr1.Number_Of_copies_existed >= jr1.Number_Of_actuel_copies) {
                    JOptionPane.showMessageDialog(this, " عذرا كل النسخ لهذا الوعاء موجودة في المكتبة");
                  
                    new Recovry().setVisible(true);
                      this.dispose();

                } else if (br.day < days) {

                    JOptionPane.showMessageDialog(this, br.Date + " ايام من  " + br.day + "  متأخر من المفترض ارجاع الوعاء بعد ");
                    i = bB.retrieve_j(jr1.Journal_ID, bB.ID);

                } else {
                    i = bB.retrieve_j(jr1.Journal_ID, bB.ID);
                }
                        
                    }}else{
                   JOptionPane.showMessageDialog(this, " يجب اختيار احدى خيارات البحث اما الرقم العام او التصنيف");
              }
                    } else if (pr.isSelected()) {
                         if (cl.isSelected()) {
                    jen.setSelected(false);

                    String data = Project.serachForProjectUsingClassification_number(sb.getText());
                    if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
                         br.ViewBorrowed2_p(sb.getText(), Integer.parseInt(ID.getText()));

                LocalDate localDate1 = LocalDate.parse(br.Date, df);
                LocalDate localDate2 = LocalDate.parse(df.format(now), df);

                long days = Period.between(localDate1, localDate2).getDays();
                System.out.println(days + "jjjjjjjjjjjjdayes heheh");
                                        System.out.println(Project.Number_Of_copies_existed);
                        System.out.println(Project.Number_Of_actuel_copies);
                        System.out.println("lkkdl");

                if (Project.Number_Of_copies_existed >= Project.Number_Of_actuel_copies) {
                    JOptionPane.showMessageDialog(this, " عذرا كل النسخ لهذا الوعاء موجودة في المكتبة");
                   
                    new Recovry().setVisible(true);
                     this.dispose();

                } else if (br.day < days) {

                    JOptionPane.showMessageDialog(this, br.Date + " ايام من  " + br.day + "  متأخر من المفترض ارجاع الوعاء بعد ");
                    i = bB.retrieve_p(Project.Project_ID, bB.ID);
                } else {

                    i = bB.retrieve_p(Project.Project_ID, bB.ID);
                }
                    }}else if(jen.isSelected()){
                         cl.setSelected(false);
                    
                     try {
                        int sb1 = Integer.parseInt(sb.getText());
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, " يجب ادخال ارقام فقط");
                    }

                    String data = Project.serachForProjectUsingID(Integer.parseInt(sb.getText()));
                    if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
                        
                   
                br.ViewBorrowed1_p(Integer.parseInt(sb.getText()), Integer.parseInt(ID.getText()));

                LocalDate localDate1 = LocalDate.parse(br.Date, df);
                LocalDate localDate2 = LocalDate.parse(df.format(now), df);

                long days = Period.between(localDate1, localDate2).getDays();
                System.out.println(days + "juuuuuuuu heheh");


                if (Project.Number_Of_copies_existed >= Project.Number_Of_actuel_copies) {
                    JOptionPane.showMessageDialog(this, " عذرا كل النسخ لهذا الوعاء موجودة في المكتبة");
                  
                    new Recovry().setVisible(true);
                      this.dispose();

                } else if (br.day < days) {

                    JOptionPane.showMessageDialog(this, br.Date + " ايام من  " + br.day + "  متأخر من المفترض ارجاع الوعاء بعد ");
                    i = bB.retrieve_p(Project.Project_ID, bB.ID);
                } else {

                    i = bB.retrieve_p(Project.Project_ID, bB.ID);
                }}
                            
            }else{
                   JOptionPane.showMessageDialog(this, " يجب اختيار احدى خيارات البحث اما الرقم العام او التصنيف");
              } }else {
                JOptionPane.showMessageDialog(this, " يجب اختيار النوع المراد البحث عنه");
            }

                    if (i == 1) {
                        JOptionPane.showMessageDialog(this, " تمت عملية الاسترجاع بنجاح");
                       
                        new Recovry().setVisible(true);
                         this.dispose();
                    } else {

                        JOptionPane.showMessageDialog(this, " عذرا عملية الاسترجاع لم تتم بنجاح");

                    }
                }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrActionPerformed
        // TODO add your handling code here:
        book.setSelected(false);
        pr.setSelected(false);
        msg.setSelected(false);
    }//GEN-LAST:event_jrActionPerformed

    private void clActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clActionPerformed
        // TODO add your handling code here:
        jen.setSelected(false);

    }//GEN-LAST:event_clActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:

        new add().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        new Search_inLibrary1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        new Library_info1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        new SearchInBorrow_s_Info1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:

        new make_a_barow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        new Recovry().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        new SearchInBorrowInfo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        new report().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        new BackUp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recovry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recovry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recovry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recovry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recovry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JRadioButton book;
    private javax.swing.JRadioButton cl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jen;
    private javax.swing.JRadioButton jr;
    private javax.swing.JRadioButton msg;
    private javax.swing.JRadioButton pr;
    private javax.swing.JTextField sb;
    // End of variables declaration//GEN-END:variables
}
