/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DB.Book;
import DB.Journal;
import DB.Messag;
import DB.Project;
import DB.borrowed;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author REEN
 */
public class report extends javax.swing.JFrame {

    /**
     * Creates new form report
     */
    public report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        broInfo = new javax.swing.JRadioButton();
        message = new javax.swing.JRadioButton();
        journal = new javax.swing.JRadioButton();
        project = new javax.swing.JRadioButton();
        book1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(187, 191, 202));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("تسجيل الخروج");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 120, 40));

        jButton10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton10.setText("حفظ");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 250, 60));

        broInfo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        broInfo.setText("بيانات الاعارة");
        broInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                broInfoActionPerformed(evt);
            }
        });
        jPanel1.add(broInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        message.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        message.setText("رسائل علمية");
        message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageActionPerformed(evt);
            }
        });
        jPanel1.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, -1, -1));

        journal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        journal.setText("دوريات");
        journal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                journalActionPerformed(evt);
            }
        });
        jPanel1.add(journal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        project.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        project.setText("مشاريع بحثية");
        project.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectActionPerformed(evt);
            }
        });
        jPanel1.add(project, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        book1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        book1.setText("كتاب");
        book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book1ActionPerformed(evt);
            }
        });
        jPanel1.add(book1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("أولا: اختر نوع المصدر");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel14.setText("انشاء تقرير ");
        jLabel14.setToolTipText("");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 430, -1));

        jButton17.setBackground(new java.awt.Color(187, 191, 202));
        jButton17.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton17.setText("اضافة الى المكتبة");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, 270, 60));

        jButton2.setBackground(new java.awt.Color(187, 191, 202));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton2.setText("البحث في المكتبة");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, 270, 60));

        jButton3.setBackground(new java.awt.Color(187, 191, 202));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton3.setText("بيانات المكتبة");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 210, 270, 60));

        jButton4.setBackground(new java.awt.Color(187, 191, 202));
        jButton4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton4.setText("بيانات المستعيرين ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 280, 270, 60));

        jButton15.setBackground(new java.awt.Color(187, 191, 202));
        jButton15.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton15.setText(" الاعارة");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 350, 270, 60));

        jButton5.setBackground(new java.awt.Color(187, 191, 202));
        jButton5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton5.setText("الاسترجاع");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 420, 270, 60));

        jButton6.setBackground(new java.awt.Color(187, 191, 202));
        jButton6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton6.setText("البحث في بيانات الاعارة");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 490, 270, 60));

        jButton7.setBackground(new java.awt.Color(187, 191, 202));
        jButton7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton7.setText("التقارير");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 560, 270, 60));

        jButton8.setBackground(new java.awt.Color(187, 191, 202));
        jButton8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton8.setText("النسخ الاحتياطي");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 630, 270, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/insert_book - Copy.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int r = JOptionPane.showConfirmDialog(this, "هل تريد تسجيل الخروج؟", "تأكيد", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (r == JOptionPane.YES_OPTION) {
          
            new User().setVisible(true);
              this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // here if user click save 
        boolean done=false;
        JFileChooser fc = null;
        File file = null;
        String name = "";
        String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());

        if (book1.isSelected()) {
            
            journal.setSelected(false);
            message.setSelected(false);
            project.setSelected(false);
            broInfo.setSelected(false);
            
            fc = new JFileChooser();
            // int result = fc.showSaveDialog(null);
            fc.showOpenDialog(this);
            //if(result == JFileChooser.APPROVE_OPTION){
            file = fc.getSelectedFile();
            name = file.getAbsolutePath();
            name = name.replace('\\', '/');
            name = name + "_" + date + ".csv";

            Book b = new Book();
            b.printReport(name);
            done = true;
            JOptionPane.showMessageDialog(this, "تم انشاء تقرير للكتب بنجاح");


        } else if (journal.isSelected()) {
            message.setSelected(false);
            project.setSelected(false);
            broInfo.setSelected(false);
            book1.setSelected(false);
            
            fc = new JFileChooser();
            // int result = fc.showSaveDialog(null);
            fc.showOpenDialog(this);
            //if(result == JFileChooser.APPROVE_OPTION){
            file = fc.getSelectedFile();
            name = file.getAbsolutePath();
            name = name.replace('\\', '/');
            name = name + "_" + date + ".csv";

            Journal j = new Journal();
            j.printReport(name);
            done = true;
            JOptionPane.showMessageDialog(this, " تم انشاء تقرير الدورية بنجاح");


        } else if (message.isSelected()){
           project.setSelected(false);
           broInfo.setSelected(false); 
           journal.setSelected(false);
           book1.setSelected(false);
           
           fc = new JFileChooser();
            // int result = fc.showSaveDialog(null);
            fc.showOpenDialog(this);
            //if(result == JFileChooser.APPROVE_OPTION){
            file = fc.getSelectedFile();
            name = file.getAbsolutePath();
            name = name.replace('\\', '/');
            name = name + "_" + date + ".csv";
            
            Messag m = new Messag();
            m.printReport(name);
            done = true;
            JOptionPane.showMessageDialog(this, " تم انشاء تقرير للرسائل بنجاح");

            
        } else if (project.isSelected()){
            broInfo.setSelected(false); 
            journal.setSelected(false);
            message.setSelected(false);
            book1.setSelected(false);
            fc = new JFileChooser();
            // int result = fc.showSaveDialog(null);
            fc.showOpenDialog(this);
            //if(result == JFileChooser.APPROVE_OPTION){
            file = fc.getSelectedFile();
            name = file.getAbsolutePath();
            name = name.replace('\\', '/');
            name = name + "_" + date + ".csv";
            
            Project p = new Project();
            p.printReport(name);
            done = true;
            JOptionPane.showMessageDialog(this, " تم انشاء تقرير للمشاريع بنجاح");

            
        } else if (broInfo.isSelected()){
            book1.setSelected(false);
            journal.setSelected(false);
            message.setSelected(false);
            project.setSelected(false);
            
            fc = new JFileChooser();
            // int result = fc.showSaveDialog(null);
            fc.showOpenDialog(this);
            //if(result == JFileChooser.APPROVE_OPTION){
            file = fc.getSelectedFile();
            name = file.getAbsolutePath();
            name = name.replace('\\', '/');
            name = name + "_" + date + ".csv";
            
            borrowed bor = new borrowed();
            bor.printBorrowInfo_b(name);
            done = true;
            JOptionPane.showMessageDialog(this, " تم انشاء تقرير لبيانات الاعارة بنجاح");

            
            
        } else {
JOptionPane.showMessageDialog(this, " يجب اختيار النوع المراد البحث عنه");
        }

        ////// JFileChooser fc = new JFileChooser();
        // int result = fc.showSaveDialog(null);
        ////fc.showOpenDialog(this);
        //if(result == JFileChooser.APPROVE_OPTION){
        ///// File file= fc.getSelectedFile(); 
        ////// String name = file.getAbsolutePath();
        ////////// name = name.replace('\\', '/');
        ///////String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
        ////////name = name +"_"+date+".csv";
        /////System.out.println(name);
        //Book b = new Book();
        //b.printReport(name);
        //Journal j = new Journal();
        //j.printReport(name);
        //Messag m = new Messag();
        //m.printReport(name);
        //Project p = new Project();
        //p.printReport(name);
        //borrowed r = new borrowed();
        //r.printBorrowInfo_b(name);
        //  }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void broInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_broInfoActionPerformed
        // TODO add your handling code here:
                journal.setSelected(false);
            message.setSelected(false);
            project.setSelected(false);
            book1.setSelected(false);
    }//GEN-LAST:event_broInfoActionPerformed

    private void book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book1ActionPerformed
        // TODO add your handling code here:
         journal.setSelected(false);
            message.setSelected(false);
            project.setSelected(false);
            broInfo.setSelected(false);
        
    }//GEN-LAST:event_book1ActionPerformed

    private void messageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageActionPerformed
        // TODO add your handling code here:
         journal.setSelected(false);
            book1.setSelected(false);
            project.setSelected(false);
            broInfo.setSelected(false);
    }//GEN-LAST:event_messageActionPerformed

    private void journalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_journalActionPerformed
        // TODO add your handling code here:
         book1.setSelected(false);
            message.setSelected(false);
            project.setSelected(false);
            broInfo.setSelected(false);
    }//GEN-LAST:event_journalActionPerformed

    private void projectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectActionPerformed
        // TODO add your handling code here:
         journal.setSelected(false);
            message.setSelected(false);
            book1.setSelected(false);
            broInfo.setSelected(false);
    }//GEN-LAST:event_projectActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:

        new add().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        new Search_inLibrary1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        new Library_info1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        new SearchInBorrow_s_Info1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:

        new make_a_barow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        new Recovry().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        new SearchInBorrowInfo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        new report().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        new BackUp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton book1;
    private javax.swing.JRadioButton broInfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton journal;
    private javax.swing.JRadioButton message;
    private javax.swing.JRadioButton project;
    // End of variables declaration//GEN-END:variables
}
