/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JOptionPane;
import DB.Book;
import DB.Journal;
import DB.Messag;
import DB.Project;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author REEN
 */
public class Search_inLibrary_helper extends javax.swing.JFrame {

    /**
     * Creates new form Search_inLibrary
     */
    public Search_inLibrary_helper() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        book = new javax.swing.JRadioButton();
        message = new javax.swing.JRadioButton();
        journal = new javax.swing.JRadioButton();
        project = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        all = new javax.swing.JRadioButton();
        bookID = new javax.swing.JRadioButton();
        c_num = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        r = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(187, 191, 202));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("تسجيل الخروج");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 120, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("أولا: اختر نوع المصدر");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, -1));

        book.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        book.setText("كتاب");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        jPanel1.add(book, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, -1, -1));

        message.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        message.setText("رسائل علمية");
        message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageActionPerformed(evt);
            }
        });
        jPanel1.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        journal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        journal.setText("دوريات");
        journal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                journalActionPerformed(evt);
            }
        });
        jPanel1.add(journal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        project.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        project.setText("مشاريع بحثية");
        project.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectActionPerformed(evt);
            }
        });
        jPanel1.add(project, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("ثانيا: اختر نوع البحث");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, -1, -1));

        all.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        all.setText("الكل ");
        all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allActionPerformed(evt);
            }
        });
        jPanel1.add(all, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, -1, -1));

        bookID.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        bookID.setText("بحث بالرقم العام ");
        bookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIDActionPerformed(evt);
            }
        });
        jPanel1.add(bookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        c_num.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        c_num.setText("بحث برقم التصنيف");
        c_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_numActionPerformed(evt);
            }
        });
        jPanel1.add(c_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("ادخل الرقم");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, -1, -1));

        num.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 280, 40));

        jButton12.setBackground(new java.awt.Color(73, 84, 100));
        jButton12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton12.setText("بحث");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 120, 40));

        r.setEditable(false);
        r.setColumns(20);
        r.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        r.setRows(5);
        jScrollPane1.setViewportView(r);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 610, 260));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel13.setText("البحث بالمكتبة");
        jLabel13.setToolTipText("");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 250, -1));

        jButton2.setBackground(new java.awt.Color(187, 191, 202));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton2.setText("البحث في المكتبة");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 220, 270, 60));

        jButton3.setBackground(new java.awt.Color(187, 191, 202));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton3.setText("بيانات المكتبة");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 300, 270, 60));

        jButton4.setBackground(new java.awt.Color(187, 191, 202));
        jButton4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton4.setText("بيانات المستعيرين ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 380, 270, 60));

        jButton6.setBackground(new java.awt.Color(187, 191, 202));
        jButton6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton6.setText("البحث في بيانات الاعارة");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 460, 270, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/insert_book - Copy.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int r = JOptionPane.showConfirmDialog(this,"هل تريد تسجيل الخروج؟","تأكيد", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(r == JOptionPane.YES_OPTION){
          
            new User().setVisible(true);
              this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        // TODO add your handling code here:
        num.setText(null);
        r.setText(null);
        message.setSelected(false);
        journal.setSelected(false);
        project.setSelected(false);
    }//GEN-LAST:event_bookActionPerformed

    private void messageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageActionPerformed
        // TODO add your handling code here:
        num.setText(null);
        r.setText(null);
        book.setSelected(false);
        journal.setSelected(false);
        project.setSelected(false);
    }//GEN-LAST:event_messageActionPerformed

    private void journalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_journalActionPerformed
        // TODO add your handling code here:
        num.setText(null);
        r.setText(null);
        message.setSelected(false);
        book.setSelected(false);
        project.setSelected(false);
    }//GEN-LAST:event_journalActionPerformed

    private void projectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectActionPerformed
        // TODO add your handling code here:
        num.setText(null);
        r.setText(null);
        message.setSelected(false);
        journal.setSelected(false);
        book.setSelected(false);
    }//GEN-LAST:event_projectActionPerformed

    private void allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allActionPerformed
        // TODO add your handling code here:
        num.disable();
        num.setBackground(Color.gray);
        num.setText(null);
        r.setText(null);
        bookID.setSelected(false);
        c_num.setSelected(false);
    }//GEN-LAST:event_allActionPerformed

    private void bookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIDActionPerformed
        // TODO add your handling code here:
        num.enable();
        num.setBackground(Color.white);
        num.setText(null);
        r.setText(null);
        all.setSelected(false);
        c_num.setSelected(false);
    }//GEN-LAST:event_bookIDActionPerformed

    private void c_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_numActionPerformed
        // TODO add your handling code here:
        num.enable();
        num.setText(null);
        r.setText(null);
        num.setBackground(Color.white);
        bookID.setSelected(false);
        all.setSelected(false);
    }//GEN-LAST:event_c_numActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        Pattern pattern;
        Matcher match;
        boolean val;
        //=================================
        if (book.isSelected()) {
            Book book = new Book();
            //**********************************case1****************************
            if (all.isSelected()) {

                String message = book.searchForAllBook();
                r.setText( message);
                //**********************************case2****************************
            } else if (bookID.isSelected()) {
                if (num.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "يجب ادخال الرقم العام  ");
                } else {
                    pattern = Pattern.compile("[^0-9]");
                    match = pattern.matcher(String.valueOf(num.getText().trim()));

                    val = match.find();
                    if (val == true) {

                        JOptionPane.showMessageDialog(this, "يجب ادخال ارقام فقط  ");
                    } else {
                        String message = book.serachForBookUsingID1(Integer.parseInt(num.getText().trim()));
                        if (message == null||message.equals("")) {
                            JOptionPane.showMessageDialog(this, "لايوجد كتاب بهذا الرقم المدخل ");
                        } else {
                            r.setText(message);
                        }
                    }
                }
                //**********************************case3****************************

            } else if (c_num.isSelected()) {
                if (num.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, " يجب ادخال رقم التصنيف");

                } else {
                    String message = book.serachForBookUsingClassification_number1(num.getText().trim());
                    System.out.println(message);
                    if (message == null||message.equals("")) {
                        JOptionPane.showMessageDialog(this, "لايوجد كتاب بهذا الرقم المدخل ");
                        // r.setText("لايوجد كتاب بهذا الرقم المدخل");
                    } else {
                        r.setText(message);
                    }
                }
            }else{

                JOptionPane.showMessageDialog(this, " يجب اختيار احدى خيارات البحث اما الرقم العام او التصنيف");
            }
            //=======================================================================================
        } else if (message.isSelected()) {
            Messag msg = new Messag();
            //**********************************case1****************************

            if (all.isSelected()) {
                String message = msg.searchForAllMsg();
                r.setText(message);
                //**********************************case2****************************

            } else if (bookID.isSelected()) {
                if (num.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "يجب ادخال الرقم العام  ");
                } else {
                    pattern = Pattern.compile("[^0-9]");
                    match = pattern.matcher(String.valueOf(num.getText().trim()));

                    val = match.find();
                    if (val == true) {

                        JOptionPane.showMessageDialog(this, "يجب ادخال ارقام فقط  ");
                    } else {

                        String message = msg.serachForMsgUsingID1(Integer.parseInt(num.getText().trim()));
                        if (message == null||message.equals("")) {
                            JOptionPane.showMessageDialog(this, "لايوجد رسالة بهذا الرقم المدخل ");
                        } else {
                            r.setText(message);
                        }
                    }

                }
                //**********************************case3****************************
            } else if (c_num.isSelected()) {
                if (num.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, " يجب ادخال رقم التصنيف");

                } else {
                    String message = msg.serachForMsgUsingClassification_number1(num.getText().trim());
                    if (message == null||message.equals("")) {
                        JOptionPane.showMessageDialog(this, "لايوجد رسالة بهذا الرقم المدخل ");
                    } else {
                        r.setText(message);
                    }
                }
            }else{

                JOptionPane.showMessageDialog(this, " يجب اختيار احدى خيارات البحث اما الرقم العام او التصنيف");
            }
            //============================================================================================
        } else if (journal.isSelected()) {
            Journal j = new Journal();
            //**********************************case1****************************
            if (all.isSelected()) {

                String message = j.searchForAllJournal();
                r.setText(message);
                //**********************************case2****************************
            } else if (bookID.isSelected()) {
                if (num.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "يجب ادخال الرقم العام  ");
                } else {
                    pattern = Pattern.compile("[^0-9]");
                    match = pattern.matcher(String.valueOf(num.getText().trim()));

                    val = match.find();
                    if (val == true) {

                        JOptionPane.showMessageDialog(this, "يجب ادخال ارقام فقط  ");
                    } else {

                        String message = j.serachForJournalUsingID1(Integer.parseInt(num.getText().trim()));
                        if (message == null||message.equals("")) {
                            JOptionPane.showMessageDialog(this, "لايوجد دورية بهذا الرقم المدخل ");
                        } else {
                            r.setText(message);
                        }
                    }
                }
                //**********************************case3****************************
            } else if (c_num.isSelected()) {
                if (num.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, " يجب ادخال رقم التصنيف");

                } else {
                    String message = j.serachForJournalUsingClassification_number1(num.getText().trim());
                    if (message == null||message.equals("")) {
                        JOptionPane.showMessageDialog(this, "لايوجد دورية بهذا الرقم المدخل ");
                    } else {
                        r.setText(message);
                    }
                }
            }else{

                JOptionPane.showMessageDialog(this, " يجب اختيار احدى خيارات البحث اما الرقم العام او التصنيف");
            }
            //==================================================================================
        } else if (project.isSelected()) {
            Project p = new Project();
            //**********************************case1****************************
            if (all.isSelected()) {
                String message = p.searchForAllProject();
                r.setText(message);
                //**********************************case2****************************
            } else if (bookID.isSelected()) {
                if (num.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "يجب ادخال الرقم العام  ");
                } else {
                    pattern = Pattern.compile("[^0-9]");
                    match = pattern.matcher(String.valueOf(num.getText().trim()));

                    val = match.find();
                    if (val == true) {

                        JOptionPane.showMessageDialog(this, "يجب ادخال ارقام فقط  ");
                    } else {

                        String message = p.serachForProjectUsingID1(Integer.parseInt(num.getText().trim()));
                        if (message == null||message.equals("")) {
                            JOptionPane.showMessageDialog(this, "لايوجد مشروع بهذا الرقم المدخل ");
                        } else {
                            r.setText(message);
                        }
                    }
                }
                //**********************************case3****************************
            } else if (c_num.isSelected()) {
                if (num.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "يجب ادخال الرقم العام  ");
                } else {
                    String message = p.serachForProjectUsingClassification_number1(num.getText().trim());
                    if (message == null||message.equals("")) {
                        JOptionPane.showMessageDialog(this, "لايوجد مشروع بهذا الرقم المدخل ");
                    } else {
                        r.setText(message);
                    }
                }
            }else{

                JOptionPane.showMessageDialog(this, " يجب اختيار احدى خيارات البحث اما الرقم العام او التصنيف");
            }
        }else{
            JOptionPane.showMessageDialog(this, " يجب اختيار النوع المراد استعارته");

        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        new Search_inLibrary_helper().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        new Library_info11().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        new SearchInBorrow_s_Info11().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        new SearchInBorrowInfo11().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_inLibrary_helper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_inLibrary_helper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_inLibrary_helper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_inLibrary_helper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_inLibrary_helper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton all;
    private javax.swing.JRadioButton book;
    private javax.swing.JRadioButton bookID;
    private javax.swing.JRadioButton c_num;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton journal;
    private javax.swing.JRadioButton message;
    private javax.swing.JTextField num;
    private javax.swing.JRadioButton project;
    private javax.swing.JTextArea r;
    // End of variables declaration//GEN-END:variables
}
