/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DB.Book;
import DB.Borrowers;
import DB.Journal;
import DB.Messag;
import DB.Project;
import DB.borrowed;
import DB.borrower_type;
import java.awt.ComponentOrientation;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author REEN
 */
public class SearchInBorrowInfo extends javax.swing.JFrame {

    /**
     * Creates new form SearchInBorrowInfo
     */
    
    borrower_type Bt;
    Borrowers bB;
    Book book1 = new Book();
    Journal jr1 = new Journal();
    Project Project = new Project();
    Messag ms = new Messag();
    borrowed br = new borrowed();
    public SearchInBorrowInfo() {
        initComponents();
         big.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cl = new javax.swing.JRadioButton();
        pr = new javax.swing.JRadioButton();
        jr = new javax.swing.JRadioButton();
        sh2 = new javax.swing.JCheckBox();
        msg = new javax.swing.JRadioButton();
        book = new javax.swing.JRadioButton();
        jen = new javax.swing.JRadioButton();
        sh1 = new javax.swing.JCheckBox();
        sb = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        big = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(187, 191, 202));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("تسجيل الخروج");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 120, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("البحث بمعلومات الوعاء");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 210, 30));

        cl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cl.setText("رقم التصنيف");
        cl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clActionPerformed(evt);
            }
        });
        jPanel1.add(cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 110, 40));

        pr.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pr.setText("مشروع");
        pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prActionPerformed(evt);
            }
        });
        jPanel1.add(pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 80, 40));

        jr.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jr.setText("دورية");
        jr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrActionPerformed(evt);
            }
        });
        jPanel1.add(jr, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 80, 40));

        sh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sh2ActionPerformed(evt);
            }
        });
        jPanel1.add(sh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, -1, -1));

        msg.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        msg.setText("رسالة");
        msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgActionPerformed(evt);
            }
        });
        jPanel1.add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 80, 40));

        book.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        book.setText("كتاب");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        jPanel1.add(book, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, 70, 40));

        jen.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jen.setText("الرقم العام");
        jen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenActionPerformed(evt);
            }
        });
        jPanel1.add(jen, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 100, 40));

        sh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sh1ActionPerformed(evt);
            }
        });
        jPanel1.add(sh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, -1, -1));

        sb.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(sb, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 360, 40));

        ID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, 360, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, 30, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("البحث بمعلومات المستعيرة");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 230, 30));

        jButton13.setBackground(new java.awt.Color(73, 84, 100));
        jButton13.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton13.setText("بحث");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 120, 40));

        big.setColumns(20);
        big.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        big.setRows(5);
        jScrollPane1.setViewportView(big);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 410, 370));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("الرقم الجامعي او الوظيفي");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 210, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("1");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 30, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("2");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 30, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setText("2");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 510, 30, 30));

        jButton9.setBackground(new java.awt.Color(73, 84, 100));
        jButton9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton9.setText("مساعدة!");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 620, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel13.setText("البحث في بيانات الاعارة");
        jLabel13.setToolTipText("");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 380, -1));

        jButton17.setBackground(new java.awt.Color(187, 191, 202));
        jButton17.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton17.setText("اضافة الى المكتبة");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, 270, 60));

        jButton2.setBackground(new java.awt.Color(187, 191, 202));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton2.setText("البحث في المكتبة");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, 270, 60));

        jButton3.setBackground(new java.awt.Color(187, 191, 202));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton3.setText("بيانات المكتبة");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 210, 270, 60));

        jButton4.setBackground(new java.awt.Color(187, 191, 202));
        jButton4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton4.setText("بيانات المستعيرين ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 280, 270, 60));

        jButton15.setBackground(new java.awt.Color(187, 191, 202));
        jButton15.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton15.setText(" الاعارة");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 350, 270, 60));

        jButton5.setBackground(new java.awt.Color(187, 191, 202));
        jButton5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton5.setText("الاسترجاع");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 420, 270, 60));

        jButton6.setBackground(new java.awt.Color(187, 191, 202));
        jButton6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton6.setText("البحث في بيانات الاعارة");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 490, 270, 60));

        jButton7.setBackground(new java.awt.Color(187, 191, 202));
        jButton7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton7.setText("التقارير");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 560, 270, 60));

        jButton8.setBackground(new java.awt.Color(187, 191, 202));
        jButton8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton8.setText("النسخ الاحتياطي");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 630, 270, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/insert_book - Copy.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int r = JOptionPane.showConfirmDialog(this,"هل تريد تسجيل الخروج؟","تأكيد", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(r == JOptionPane.YES_OPTION){
         
            new User().setVisible(true);
               this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenActionPerformed
        // TODO add your handling code here:
         cl.setSelected(false);
    }//GEN-LAST:event_jenActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:

        if(sh1.isSelected()&& sh2.isSelected()){
            
              if (ID.getText().isEmpty() || sb.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, " الرجاء تعبئة جميع الحقول ");

        } else {
             bB = new Borrowers(Integer.parseInt(ID.getText()));
         Pattern pattern = Pattern.compile("[^0-9]");
            Matcher match = pattern.matcher(String.valueOf(bB.ID));

            boolean val = match.find();

            if (val == true) {

                JOptionPane.showMessageDialog(this, "عذرا يجب ادخال الرقم الجامعي او الوظيفي بشكل صحيح ");
            }
        
                    
      
        boolean check = bB.search(bB.ID);
        if (check) {
            
            Bt = new borrower_type();
            Bt.search(bB.type);
          
        } else {
            JOptionPane.showMessageDialog(this, " رقم المستخدم غير موجود");
        }
              if (book.isSelected()) {

                  if (jen.isSelected()){
                      
                  
                    try {
                        int sb1 = Integer.parseInt(sb.getText());
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, " يجب ادخال ارقام فقط");
                    }
        
              String data=  book1.serachForBookUsingID(Integer.parseInt(sb.getText()));
                if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
               int res= br.ViewBorrowed1(book1.book_ID, bB.ID);
               
               if(res==0){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{

                String m = +br.Borro+"  --  "+"الرقم الجامعي او الوظيفي  \n"+ Bt.type+"  --  "+" فئة المستعير \n"+br.ID+"  --  "+" رقم عملية الاعارة\n"+br.day+"  --  "+ "مدة الاعارة بالايام\n "+br.itm+"  --  "+"الرقم العام للوعاء المستعار\n "+br.Date+"  --  "+" تاريخ الاستعارة\n"+br.State+"  --  "+" حالة الاعارة\n";
                big.setText(m);

           
            }}} else if (cl.isSelected()) {

              String data=  book1.serachForBookUsingClassification_number(sb.getText());
              
               if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
              
             int res= br.ViewBorrowed2(book1.Classification_number, bB.ID);
             
                 if(res==0){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{
              
                String m = +br.Borro+"  --  "+"الرقم الجامعي او الوظيفي  \n"+ Bt.type+"  --  "+" فئة المستعير \n"+br.ID+"  --  "+" رقم عملية الاعارة\n"+br.day+"  --  "+ "مدة الاعارة بالايام\n "+br.itm+"  --  "+"الرقم العام للوعاء المستعار\n "+br.Date+"  --  "+" تاريخ الاستعارة\n"+br.State+"  --  "+" حالة الاعارة\n";
                big.setText(m);

            }}} else {

                JOptionPane.showMessageDialog(this, " يجب اختيار احدى خيارات البحث اما الرقم العام او التصنيف");

            }
            
            
          } else if (jr.isSelected()) {

             if (jen.isSelected()){
                 
                   try {
                        int sb1 = Integer.parseInt(sb.getText());
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, " يجب ادخال ارقام فقط");
                    }
      
              String data=  jr1.serachForJournalUsingID(Integer.parseInt(sb.getText()));
              if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
            int res= br.ViewBorrowed1_j(jr1.Journal_ID, bB.ID);
              if(res==0){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{
              
              String m = +br.Borro+"  --  "+"الرقم الجامعي او الوظيفي  \n"+ Bt.type+"  --  "+" فئة المستعير \n"+br.ID+"  --  "+" رقم عملية الاعارة\n"+br.day+"  --  "+ "مدة الاعارة بالايام\n "+br.itm+"  --  "+"الرقم العام للوعاء المستعار\n "+br.Date+"  --  "+" تاريخ الاستعارة\n"+br.State+"  --  "+" حالة الاعارة\n";
                big.setText(m);

           
            }}} else if (cl.isSelected()) {

              String data=  jr1.serachForJournalUsingClassification_number(sb.getText());
               if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
              
             int res= br.ViewBorrowed2_j(jr1.Classification_number, bB.ID);
               if(res==0){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{
              
                String m = +br.Borro+"  --  "+"الرقم الجامعي او الوظيفي  \n"+ Bt.type+"  --  "+" فئة المستعير \n"+br.ID+"  --  "+" رقم عملية الاعارة\n"+br.day+"  --  "+ "مدة الاعارة بالايام\n "+br.itm+"  --  "+"الرقم العام للوعاء المستعار\n "+br.Date+"  --  "+" تاريخ الاستعارة\n"+br.State+"  --  "+" حالة الاعارة\n";
                big.setText(m);
        
            }}}else{
               
                JOptionPane.showMessageDialog(this, " يجب اختيار احدى خيارات البحث اما الرقم العام او التصنيف");
           
            }

          }else if(pr.isSelected()) {

             if (jen.isSelected()){
      
                   try {
                        int sb1 = Integer.parseInt(sb.getText());
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, " يجب ادخال ارقام فقط");
                    }
              String data=  Project.serachForProjectUsingID(Integer.parseInt(sb.getText()));
               if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
             int res= br.ViewBorrowed1_p(Project.Project_ID, bB.ID);
               if(res==0){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{
              
               String m = +br.Borro+"  --  "+"الرقم الجامعي او الوظيفي  \n"+ Bt.type+"  --  "+" فئة المستعير \n"+br.ID+"  --  "+" رقم عملية الاعارة\n"+br.day+"  --  "+ "مدة الاعارة بالايام\n "+br.itm+"  --  "+"الرقم العام للوعاء المستعار\n "+br.Date+"  --  "+" تاريخ الاستعارة\n"+br.State+"  --  "+" حالة الاعارة\n";
                big.setText(m);

           
            }}} else if (cl.isSelected()) {

              String data=  Project.serachForProjectUsingClassification_number(sb.getText());
                if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
            int res=  br.ViewBorrowed2_p(Project.Classification_number, bB.ID);
             if(res==0){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{
              
               String m = +br.Borro+"  --  "+"الرقم الجامعي او الوظيفي  \n"+ Bt.type+"  --  "+" فئة المستعير \n"+br.ID+"  --  "+" رقم عملية الاعارة\n"+br.day+"  --  "+ "مدة الاعارة بالايام\n "+br.itm+"  --  "+"الرقم العام للوعاء المستعار\n "+br.Date+"  --  "+" تاريخ الاستعارة\n"+br.State+"  --  "+" حالة الاعارة\n";
                big.setText(m);
        
            }}} else {

                      JOptionPane.showMessageDialog(this, " يجب اختيار احدى خيارات البحث اما الرقم العام او التصنيف");

                  }

              } else if (msg.isSelected()) {

                 if (jen.isSelected()){
                       try {
                        int sb1 = Integer.parseInt(sb.getText());
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, " يجب ادخال ارقام فقط");
                    }
      
              String data=  ms.serachForMsgUsingID(Integer.parseInt(sb.getText()));
               if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
             int res= br.ViewBorrowed1_l(ms.msg_id, bB.ID);
              if(res==0){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{
              
              String m = +br.Borro+"  --  "+"الرقم الجامعي او الوظيفي  \n"+ Bt.type+"  --  "+" فئة المستعير \n"+br.ID+"  --  "+" رقم عملية الاعارة\n"+br.day+"  --  "+ "مدة الاعارة بالايام\n "+br.itm+"  --  "+"الرقم العام للوعاء المستعار\n "+br.Date+"  --  "+" تاريخ الاستعارة\n"+br.State+"  --  "+" حالة الاعارة\n";
                big.setText(m);

           
            }}} else if (cl.isSelected()) {

              String data=  ms.serachForMsgUsingClassification_number(sb.getText());
               if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
             int res= br.ViewBorrowed2_l(ms.Classification_number, bB.ID);
               if(res==0){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{
              
              String m = +br.Borro+"  --  "+"الرقم الجامعي او الوظيفي  \n"+ Bt.type+"  --  "+" فئة المستعير \n"+br.ID+"  --  "+" رقم عملية الاعارة\n"+br.day+"  --  "+ "مدة الاعارة بالايام\n "+br.itm+"  --  "+"الرقم العام للوعاء المستعار\n "+br.Date+"  --  "+" تاريخ الاستعارة\n"+br.State+"  --  "+" حالة الاعارة\n";
                big.setText(m);
        
            }}}else{
               
                JOptionPane.showMessageDialog(this, " يجب اختيار احدى خيارات البحث اما الرقم العام او التصنيف");
           
            }
               
                
                
          }else{
               
                JOptionPane.showMessageDialog(this, " يجب اختيار النوع المراد البحث عنه");
           
            }
              }  
            
           //////////////////////// 
        }else if(sh1.isSelected()){
             if (sb.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, " الرجاء تعبئة جميع الحقول ");

        } else {
            
            if (book.isSelected()) {
                if (jen.isSelected()) {
                      try {
                        int sb1 = Integer.parseInt(sb.getText());
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, " يجب ادخال ارقام فقط");
                    }

                    String data = book1.serachForBookUsingID(Integer.parseInt(sb.getText()));
                     if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
                    
                  String m = br.ViewBorrowed1_i(book1.book_ID);
                  
                   if(m.equals("")){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{
                  

                  //  String m = br.Borro + "/" + br.Con + "/" + br.ID + "/" + br.day + "/" + br.itm + "/" + br.Date + "/" + br.State;
                    big.setText(m);

           
            }}} else if (cl.isSelected()) {

              String data=  book1.serachForBookUsingClassification_number(sb.getText());
              if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
             String m = br.ViewBorrowed2_i(book1.Classification_number);
              if(m.equals("")){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{
              
            //   String m = br.Borro+"/"+br.Con+"/"+br.ID+"/"+br.day+"/"+br.itm+"/"+br.Date+"/"+br.State;
                big.setText(m);

            }}} else {

                JOptionPane.showMessageDialog(this, " يجب اختيار احدى خيارات البحث اما الرقم العام او التصنيف");

            }
            
            
          } else if (jr.isSelected()) {

             if (jen.isSelected()){
                   try {
                        int sb1 = Integer.parseInt(sb.getText());
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, " يجب ادخال ارقام فقط");
                    }
      
              String data=  jr1.serachForJournalUsingID(Integer.parseInt(sb.getText()));
              if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
             String m = br.ViewBorrowed1_ji(jr1.Journal_ID);
               if(m.equals("")){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{
              
               //String m = br.Borro+"/"+br.Con+"/"+br.ID+"/"+br.day+"/"+br.itm+"/"+br.Date+"/"+br.State;
                big.setText(m);

           
            }}} else if (cl.isSelected()) {

              String data=  jr1.serachForJournalUsingClassification_number(sb.getText());
               if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
              String m =br.ViewBorrowed2_ji(jr1.Classification_number);
               if(m.equals("")){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{
              
              // String m = br.Borro+"/"+br.Con+"/"+br.ID+"/"+br.day+"/"+br.itm+"/"+br.Date+"/"+br.State;
                big.setText(m);
        
            }}}else{
               
                JOptionPane.showMessageDialog(this, " يجب اختيار احدى خيارات البحث اما الرقم العام او التصنيف");
           
            }

          }else if(pr.isSelected()) {

             if (jen.isSelected()){
                   try {
                        int sb1 = Integer.parseInt(sb.getText());
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, " يجب ادخال ارقام فقط");
                    }
      
              String data=  Project.serachForProjectUsingID(Integer.parseInt(sb.getText()));
               if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
             String m = br.ViewBorrowed1_pi(Project.Project_ID);
               if(m.equals("")){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{
              // String m = br.Borro+"/"+br.Con+"/"+br.ID+"/"+br.day+"/"+br.itm+"/"+br.Date+"/"+br.State;
                big.setText(m);

           
            }}} else if (cl.isSelected()) {

              String data=  Project.serachForProjectUsingClassification_number(sb.getText());
               if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
             String m = br.ViewBorrowed2_pi(Project.Classification_number);
                if(m.equals("")){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{
              // String m = br.Borro+"/"+br.Con+"/"+br.ID+"/"+br.day+"/"+br.itm+"/"+br.Date+"/"+br.State;
                big.setText(m);
        
            }}} else {

                      JOptionPane.showMessageDialog(this, " يجب اختيار احدى خيارات البحث اما الرقم العام او التصنيف");

                  }

              } else if (msg.isSelected()) {

                 if (jen.isSelected()){
      
                       try {
                        int sb1 = Integer.parseInt(sb.getText());
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, " يجب ادخال ارقام فقط");
                    }
              String data=  ms.serachForMsgUsingID(Integer.parseInt(sb.getText()));
                if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
             String m = br.ViewBorrowed1_li(ms.msg_id);
               if(m.equals("")){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{
              // String m = br.Borro+"/"+br.Con+"/"+br.ID+"/"+br.day+"/"+br.itm+"/"+br.Date+"/"+br.State;
                big.setText(m);

           
            }}} else if (cl.isSelected()) {

              String data=  ms.serachForMsgUsingClassification_number(sb.getText());
              if (data == null) {
                        JOptionPane.showMessageDialog(this, " لايوجد وعاء بحسب البيانات المختارة");

                    } else {
             String m = br.ViewBorrowed2_li(ms.Classification_number);
                if(m.equals("")){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{
              // String m = br.Borro+"/"+br.Con+"/"+br.ID+"/"+br.day+"/"+br.itm+"/"+br.Date+"/"+br.State;
                big.setText(m);
        
            }}}else{
               
                JOptionPane.showMessageDialog(this, " يجب اختيار احدى خيارات البحث اما الرقم العام او التصنيف");
           
            }
               
                
                
          }else{
               
                JOptionPane.showMessageDialog(this, " يجب اختيار النوع المراد البحث عنه");
           
            }
            
            
        }}else if(sh2.isSelected()){
              if (ID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, " الرجاء تعبئة جميع الحقول ");

        } else {
           bB = new Borrowers(Integer.parseInt(ID.getText()));
         Pattern pattern = Pattern.compile("[^0-9]");
            Matcher match = pattern.matcher(String.valueOf(bB.ID));

            boolean val = match.find();

            if (val == true) {

                JOptionPane.showMessageDialog(this, "عذرا يجب ادخال الرقم الجامعي او الوظيفي بشكل صحيح ");
            }
        
                    
            
        boolean check = bB.search(bB.ID);
        if (check) {
            Bt = new borrower_type();
            Bt.search(bB.type);
            //  System.out.println(bB.ID + "  " + Bt.type + "  " + bB.name);
        } else {
                JOptionPane.showMessageDialog(this, " رقم المستخدم غير موجود");
            }
            if (book.isSelected()) {
                String m = br.ViewBorrowed_id(bB.ID);
                 if(m.equals("")){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{
                big.setText(m);

            }} else if (msg.isSelected()) {
                String m = br.ViewBorrowed_lid(bB.ID);
                 if(m.equals("")){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{
                big.setText(m);
            }} else if (pr.isSelected()) {
                String m = br.ViewBorrowed_pid(bB.ID);
                 if(m.equals("")){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{
                big.setText(m);
            }} else if (jr.isSelected()) {
                String m = br.ViewBorrowed_jid(bB.ID);
                 if(m.equals("")){
                    JOptionPane.showMessageDialog(this, " لايوجد عملية اعارة بالبيانات المدخلة");
                   
               }else{
                big.setText(m);
            }} else {

             JOptionPane.showMessageDialog(this, " يجب اختيار النوع المراد البحث عنه");
            }
            
        }}else{
            JOptionPane.showMessageDialog(this, " يرجى اختيار طريقة البحث");
        }
 
      //  br.ViewBorrowed1(3, 1234);

    
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prActionPerformed
        // TODO add your handling code here:
        book.setSelected(false);
        jr.setSelected(false);
        msg.setSelected(false);
    }//GEN-LAST:event_prActionPerformed

    private void jrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrActionPerformed
        // TODO add your handling code here:
        book.setSelected(false);
        pr.setSelected(false);
        msg.setSelected(false);
    }//GEN-LAST:event_jrActionPerformed

    private void msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgActionPerformed
        // TODO add your handling code here:
        book.setSelected(false);
        jr.setSelected(false);
        pr.setSelected(false);
    }//GEN-LAST:event_msgActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        // TODO add your handling code here:
        msg.setSelected(false);
        jr.setSelected(false);
        pr.setSelected(false);
    }//GEN-LAST:event_bookActionPerformed

    private void sh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sh1ActionPerformed
        // TODO add your handling code here:
        // sh2.setSelected(false);
    }//GEN-LAST:event_sh1ActionPerformed

    private void sh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sh2ActionPerformed
        // TODO add your handling code here:
        // sh1.setSelected(false);
    }//GEN-LAST:event_sh2ActionPerformed

    private void clActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clActionPerformed
        // TODO add your handling code here:
         jen.setSelected(false);
        
    }//GEN-LAST:event_clActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "يمكنك البحث باستخدام معلومات الوعاء و معلومات المستعيرة \n"
            + "او البحث بمعلومات الوعاء فقط \n"
            + "او البحث بمعلومات المستعير فقط \n"
            + "** ولكن يجب اختيار النوع المراد البحث عنه عند البحث بمعلومات المستعير فقط و يجب اختيار النوع المراد البحث عنه\n و طريقة البحث عند البحث بمعلومات الوعاد فقط و يجب اختيار جميع ماسبق عند البحث بمعلومات الوعاء ومعلومات المستعير معا **");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:

        new add().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        new Search_inLibrary1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        new Library_info1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        new SearchInBorrow_s_Info1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:

        new make_a_barow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        new Recovry().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        new SearchInBorrowInfo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        new report().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        new BackUp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchInBorrowInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchInBorrowInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchInBorrowInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchInBorrowInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchInBorrowInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JTextArea big;
    private javax.swing.JRadioButton book;
    private javax.swing.JRadioButton cl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jen;
    private javax.swing.JRadioButton jr;
    private javax.swing.JRadioButton msg;
    private javax.swing.JRadioButton pr;
    private javax.swing.JTextField sb;
    private javax.swing.JCheckBox sh1;
    private javax.swing.JCheckBox sh2;
    // End of variables declaration//GEN-END:variables
}
